config/routes.rb
ChangeServer::Application.routes.draw do
  root :to => 'scores#index'

  resources :scores
end

app/models/score.rb
class Score < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :scores

  attr_accessible :facebook_id, :name, :email
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController

  before_filter :init_facebook_api, :except => [:index, :new]


  def index

  end

  def new
    @settings = FACEBOOK
  end

  def create
    profile = @api.get_object "me"
    name = profile['name']
    facebook_id = profile['id']
    email = profile['email']

    user = User.new
    user.name = name
    user.facebook_id = facebook_id
    user.email = email
    user.save!

    score = Score.new
    score.score = params[:score]
    score.user = user
    score.save!

    render :nothing => true
  end

  def init_facebook_api
    oauth = Koala::Facebook::OAuth.new(FACEBOOK['app_id'], FACEBOOK['secret'])
    facebook_user = oauth.get_user_info_from_cookies(cookies)
    @api = Koala::Facebook::API.new facebook_user['access_token']
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/scores_helper.rb
module ScoresHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ChangeServer</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/scores/index.html.haml
%h1 Change server
!= link_to "Create new score", new_score_path

app/views/scores/new.html.haml
#fb-root
:javascript
  window.fbAsyncInit = function() {
    FB.init({
      appId      : "#{@settings['app_id']}", // App ID
      channelUrl : "//#{request.domain}/channel.html", // Channel File
      status     : true, // check login status
      cookie     : true, // enable cookies to allow the server to access the session
      xfbml      : true  // parse XFBML
    });

    var passed_auth = false;

    // Additional initialization code here
    $("#scores_form").submit(function() {
      debugger;
      if (passed_auth) {
        return true;
      } else {
        FB.login(function(response) {
          passed_auth = true;
          console.log(response);
          $("#scores_form").submit();
        });

        return false;
      }
    });
  };

  // Load the SDK Asynchronously
  (function(d){
     var js, id = 'facebook-jssdk', ref = d.getElementsByTagName('script')[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement('script'); js.id = id; js.async = true;
     js.src = "//connect.facebook.net/en_US/all.js";
     ref.parentNode.insertBefore(js, ref);
  }(document));

!= form_tag('/scores', :id => "scores_form") do
  %label{:for => "score"} Enter your score
  %input#score{:name => "score", :type => :text}
  %input#login{:type => :submit}